version: ^3.1
services: 
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environments:
      MYSQL_DATABASE: cuidapet_db2
      MYSQL_ROOT_PASSWORD: Cuidapetdb2
    volumes:
      - ../mysql_data:/var/lib/mysql